version: '3.8'
services:
  web:
    image: multi-container-app-web
    expose:
      - "5002"
    depends_on:
      - myredis
  nginx:
    image: nginx:latest
    ports:
    - "5002:5002"
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
    - web


  myredis:
    image: "redis:alpine"
    ports:
    - "6379"
    volumes: 
    - redis-data:/data 
    
volumes:
  redis-data: