version: '3.8'
services:
  web:
    image: multi-container-app-web
    ports:
      - "5002:5002"
    depends_on:
      - myredis
  myredis:
    image: "redis:alpine"
    ports:
    - "6379"
    volumes: 
    - redis-data:/data 
    
volumes:
  redis-data: